services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: mariadb_movies_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: movies_db
      MYSQL_USER: movie_user
      MYSQL_PASSWORD: movie_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql # Use local data directory for persistence
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize schema
    restart: always

  scrapper_service:
    build:
      context: ./scrapper
      dockerfile: Dockerfile
    container_name: scrapper_service_container
    ports:
      - "5001:5000" # Expose the Flask app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: movie_user
      DB_PASSWORD: movie_password
      DB_DATABASE: movies_db
    restart: always

  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    container_name: scheduler_service_container
    depends_on:
      - scrapper_service
    environment:
      SCRAPER_URL: http://172.17.0.1:5001/scraper
      BOT_URL: http://172.17.0.1:5002/send_movies
      RUN_HOUR: 7  # Scheduler runtime
      RUN_MINUTE: 0
      TZ: America/Mexico_City
    restart: always
      
  bot_service:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot_service_container
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=movie_user
      - DB_PASSWORD=movie_password
      - DB_DATABASE=movies_db
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - SCRAPPER_URL=${SCRAPPER_URL}
      - TELEGRAM_USER_ID=${TELEGRAM_USER_ID}
    ports:
      - "5002:5002"
    restart: always
    
volumes:
  db_data:
  
