name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Use the self-hosted runner
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
              
      - name: Debug: Print Working Directory
        run: |
          echo "Current directory is:"
          pwd
          echo "Listing current directory contents:"
          ls -lah

      - name: Docker Compose Down
        run: |
          docker compose down

      - name: Docker Compose Build
        run: |
          docker-compose build

      - name: Docker Compose Up
        run: |
          docker compose up -d
